var wms_layers = [];


        var lyr_OSMStandard_0 = new ol.layer.Tile({
            'title': 'OSM Standard',
            'type': 'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
    attributions: ' &middot; <a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors, CC-BY-SA</a>',
                url: 'http://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_KinondoniDistrictBoundary_1 = new ol.format.GeoJSON();
var features_KinondoniDistrictBoundary_1 = format_KinondoniDistrictBoundary_1.readFeatures(json_KinondoniDistrictBoundary_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_KinondoniDistrictBoundary_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_KinondoniDistrictBoundary_1.addFeatures(features_KinondoniDistrictBoundary_1);
var lyr_KinondoniDistrictBoundary_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_KinondoniDistrictBoundary_1, 
                style: style_KinondoniDistrictBoundary_1,
                interactive: true,
                title: '<img src="styles/legend/KinondoniDistrictBoundary_1.png" /> Kinondoni District Boundary'
            });
var format_HIVHotspost_2 = new ol.format.GeoJSON();
var features_HIVHotspost_2 = format_HIVHotspost_2.readFeatures(json_HIVHotspost_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_HIVHotspost_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_HIVHotspost_2.addFeatures(features_HIVHotspost_2);
var lyr_HIVHotspost_2 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_HIVHotspost_2, 
                style: style_HIVHotspost_2,
                interactive: true,
    title: 'HIV Hotspost<br />\
    <img src="styles/legend/HIVHotspost_2_0.png" /> Bar<br />\
    <img src="styles/legend/HIVHotspost_2_1.png" /> Bus station<br />\
    <img src="styles/legend/HIVHotspost_2_2.png" /> Cinema<br />\
    <img src="styles/legend/HIVHotspost_2_3.png" /> Marketplace<br />\
    <img src="styles/legend/HIVHotspost_2_4.png" /> Nightclub<br />'
        });
var format_TestingFacilities_3 = new ol.format.GeoJSON();
var features_TestingFacilities_3 = format_TestingFacilities_3.readFeatures(json_TestingFacilities_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_TestingFacilities_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_TestingFacilities_3.addFeatures(features_TestingFacilities_3);
var lyr_TestingFacilities_3 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_TestingFacilities_3, 
                style: style_TestingFacilities_3,
                interactive: true,
    title: 'Testing Facilities<br />\
    <img src="styles/legend/TestingFacilities_3_0.png" /> Clinic<br />\
    <img src="styles/legend/TestingFacilities_3_1.png" /> Hospital<br />\
    <img src="styles/legend/TestingFacilities_3_2.png" /> Pharmacy<br />'
        });

lyr_OSMStandard_0.setVisible(true);lyr_KinondoniDistrictBoundary_1.setVisible(true);lyr_HIVHotspost_2.setVisible(true);lyr_TestingFacilities_3.setVisible(true);
var layersList = [lyr_OSMStandard_0,lyr_KinondoniDistrictBoundary_1,lyr_HIVHotspost_2,lyr_TestingFacilities_3];
lyr_KinondoniDistrictBoundary_1.set('fieldAliases', {'Id': 'Id', 'Name': 'Name', });
lyr_HIVHotspost_2.set('fieldAliases', {'full_id': 'full_id', 'osm_id': 'osm_id', 'osm_type': 'osm_type', 'amenity': 'amenity', 'highway': 'highway', 'addr:city': 'addr:city', 'addr:district': 'addr:district', 'addr:municipality': 'addr:municipality', 'name': 'name', 'name:en': 'name:en', 'religion': 'religion', 'shop': 'shop', 'cargo': 'cargo', 'operator': 'operator', 'cuisine': 'cuisine', 'addr:housename': 'addr:housename', 'addr:housenumber': 'addr:housenumber', 'addr:postcode': 'addr:postcode', 'addr:street': 'addr:street', 'description': 'description', 'website': 'website', 'outdoor_seating': 'outdoor_seating', 'wheelchair': 'wheelchair', 'brand': 'brand', 'fuel:octane_95': 'fuel:octane_95', 'opening_hours': 'opening_hours', 'toilets:wheelchair': 'toilets:wheelchair', 'country': 'country', 'target': 'target', 'phone': 'phone', 'alt_name': 'alt_name', 'brand:wikidata': 'brand:wikidata', 'brand:wikipedia': 'brand:wikipedia', 'takeaway': 'takeaway', 'bicycle_parking': 'bicycle_parking', 'access': 'access', 'smoothness': 'smoothness', 'surface': 'surface', 'Catering': 'Catering', 'delivery': 'delivery', 'atm': 'atm', 'natural': 'natural', 'bench': 'bench', 'level': 'level', 'email': 'email', 'smoking': 'smoking', 'noname': 'noname', 'fee': 'fee', 'operator:type': 'operator:type', 'contact:phone': 'contact:phone', 'capacity': 'capacity', 'name:sw': 'name:sw', 'internet_access': 'internet_access', 'studio': 'studio', 'fuel': 'fuel', 'denomination': 'denomination', 'toilets:access': 'toilets:access', 'toilets:disposal': 'toilets:disposal', 'toilets:handwashing': 'toilets:handwashing', 'toilets:num_chambers': 'toilets:num_chambers', 'man_made': 'man_made', 'activities': 'activities', 'ancillary_services': 'ancillary_services', 'dispensing': 'dispensing', 'emergency': 'emergency', 'healthcare': 'healthcare', 'healthcare:speciality': 'healthcare:speciality', 'scope': 'scope', 'service_times': 'service_times', 'nature': 'nature', 'network': 'network', 'building': 'building', 'tourism': 'tourism', 'landuse': 'landuse', 'waste': 'waste', 'social_facility': 'social_facility', 'addr:subward': 'addr:subward', 'addr:ward': 'addr:ward', 'cash_in': 'cash_in', 'currency:TZS': 'currency:TZS', 'drive_through': 'drive_through', 'Ward': 'Ward', 'power': 'power', 'diet:vegetarian': 'diet:vegetarian', 'diet:vegan': 'diet:vegan', 'opening_hours:kitchen': 'opening_hours:kitchen', 'addr:country': 'addr:country', 'cash_withdrawal': 'cash_withdrawal', 'self_service': 'self_service', 'toilets': 'toilets', 'layer': 'layer', 'path': 'path', });
lyr_TestingFacilities_3.set('fieldAliases', {'full_id': 'full_id', 'osm_id': 'osm_id', 'osm_type': 'osm_type', 'amenity': 'amenity', 'highway': 'highway', 'addr_city': 'addr_city', 'addr_distr': 'addr_distr', 'addr_munic': 'addr_munic', 'name': 'name', 'name_en': 'name_en', 'religion': 'religion', 'shop': 'shop', 'cargo': 'cargo', 'operator': 'operator', 'cuisine': 'cuisine', 'addr_house': 'addr_house', 'addr_hou_1': 'addr_hou_1', 'addr_postc': 'addr_postc', 'addr_stree': 'addr_stree', 'descriptio': 'descriptio', 'website': 'website', 'outdoor_se': 'outdoor_se', 'wheelchair': 'wheelchair', 'brand': 'brand', 'fuel_octan': 'fuel_octan', 'opening_ho': 'opening_ho', 'toilets_wh': 'toilets_wh', 'country': 'country', 'target': 'target', 'phone': 'phone', 'alt_name': 'alt_name', 'brand_wiki': 'brand_wiki', 'brand_wi_1': 'brand_wi_1', 'takeaway': 'takeaway', 'bicycle_pa': 'bicycle_pa', 'access': 'access', 'smoothness': 'smoothness', 'surface': 'surface', 'Catering': 'Catering', 'delivery': 'delivery', 'atm': 'atm', 'natural': 'natural', 'bench': 'bench', 'level': 'level', 'email': 'email', 'smoking': 'smoking', 'noname': 'noname', 'fee': 'fee', 'operator_t': 'operator_t', 'contact_ph': 'contact_ph', 'capacity': 'capacity', 'name_sw': 'name_sw', 'internet_a': 'internet_a', 'studio': 'studio', 'fuel': 'fuel', 'denominati': 'denominati', 'toilets_ac': 'toilets_ac', 'toilets_di': 'toilets_di', 'toilets_ha': 'toilets_ha', 'toilets_nu': 'toilets_nu', 'man_made': 'man_made', 'activities': 'activities', 'ancillary_': 'ancillary_', 'dispensing': 'dispensing', 'emergency': 'emergency', 'healthcare': 'healthcare', 'healthca_1': 'healthca_1', 'scope': 'scope', 'service_ti': 'service_ti', 'nature': 'nature', 'network': 'network', 'building': 'building', 'tourism': 'tourism', 'landuse': 'landuse', 'waste': 'waste', 'social_fac': 'social_fac', 'addr_subwa': 'addr_subwa', 'addr_ward': 'addr_ward', 'cash_in': 'cash_in', 'currency_T': 'currency_T', 'drive_thro': 'drive_thro', 'Ward': 'Ward', 'power': 'power', 'diet_veget': 'diet_veget', 'diet_vegan': 'diet_vegan', 'opening__1': 'opening__1', 'addr_count': 'addr_count', 'cash_withd': 'cash_withd', 'self_servi': 'self_servi', 'toilets': 'toilets', });
lyr_KinondoniDistrictBoundary_1.set('fieldImages', {'Id': 'Range', 'Name': 'TextEdit', });
lyr_HIVHotspost_2.set('fieldImages', {'full_id': 'TextEdit', 'osm_id': 'TextEdit', 'osm_type': 'TextEdit', 'amenity': 'TextEdit', 'highway': 'TextEdit', 'addr:city': 'TextEdit', 'addr:district': 'TextEdit', 'addr:municipality': 'TextEdit', 'name': 'TextEdit', 'name:en': 'TextEdit', 'religion': 'TextEdit', 'shop': 'TextEdit', 'cargo': 'TextEdit', 'operator': 'TextEdit', 'cuisine': 'TextEdit', 'addr:housename': 'TextEdit', 'addr:housenumber': 'TextEdit', 'addr:postcode': 'TextEdit', 'addr:street': 'TextEdit', 'description': 'TextEdit', 'website': 'TextEdit', 'outdoor_seating': 'TextEdit', 'wheelchair': 'TextEdit', 'brand': 'TextEdit', 'fuel:octane_95': 'TextEdit', 'opening_hours': 'TextEdit', 'toilets:wheelchair': 'TextEdit', 'country': 'TextEdit', 'target': 'TextEdit', 'phone': 'TextEdit', 'alt_name': 'TextEdit', 'brand:wikidata': 'TextEdit', 'brand:wikipedia': 'TextEdit', 'takeaway': 'TextEdit', 'bicycle_parking': 'TextEdit', 'access': 'TextEdit', 'smoothness': 'TextEdit', 'surface': 'TextEdit', 'Catering': 'TextEdit', 'delivery': 'TextEdit', 'atm': 'TextEdit', 'natural': 'TextEdit', 'bench': 'TextEdit', 'level': 'TextEdit', 'email': 'TextEdit', 'smoking': 'TextEdit', 'noname': 'TextEdit', 'fee': 'TextEdit', 'operator:type': 'TextEdit', 'contact:phone': 'TextEdit', 'capacity': 'TextEdit', 'name:sw': 'TextEdit', 'internet_access': 'TextEdit', 'studio': 'TextEdit', 'fuel': 'TextEdit', 'denomination': 'TextEdit', 'toilets:access': 'TextEdit', 'toilets:disposal': 'TextEdit', 'toilets:handwashing': 'TextEdit', 'toilets:num_chambers': 'TextEdit', 'man_made': 'TextEdit', 'activities': 'TextEdit', 'ancillary_services': 'TextEdit', 'dispensing': 'TextEdit', 'emergency': 'TextEdit', 'healthcare': 'TextEdit', 'healthcare:speciality': 'TextEdit', 'scope': 'TextEdit', 'service_times': 'TextEdit', 'nature': 'TextEdit', 'network': 'TextEdit', 'building': 'TextEdit', 'tourism': 'TextEdit', 'landuse': 'TextEdit', 'waste': 'TextEdit', 'social_facility': 'TextEdit', 'addr:subward': 'TextEdit', 'addr:ward': 'TextEdit', 'cash_in': 'TextEdit', 'currency:TZS': 'TextEdit', 'drive_through': 'TextEdit', 'Ward': 'TextEdit', 'power': 'TextEdit', 'diet:vegetarian': 'TextEdit', 'diet:vegan': 'TextEdit', 'opening_hours:kitchen': 'TextEdit', 'addr:country': 'TextEdit', 'cash_withdrawal': 'TextEdit', 'self_service': 'TextEdit', 'toilets': 'TextEdit', 'layer': 'TextEdit', 'path': 'TextEdit', });
lyr_TestingFacilities_3.set('fieldImages', {'full_id': 'TextEdit', 'osm_id': 'TextEdit', 'osm_type': 'TextEdit', 'amenity': 'TextEdit', 'highway': 'TextEdit', 'addr_city': 'TextEdit', 'addr_distr': 'TextEdit', 'addr_munic': 'TextEdit', 'name': 'TextEdit', 'name_en': 'TextEdit', 'religion': 'TextEdit', 'shop': 'TextEdit', 'cargo': 'TextEdit', 'operator': 'TextEdit', 'cuisine': 'TextEdit', 'addr_house': 'TextEdit', 'addr_hou_1': 'TextEdit', 'addr_postc': 'TextEdit', 'addr_stree': 'TextEdit', 'descriptio': 'TextEdit', 'website': 'TextEdit', 'outdoor_se': 'TextEdit', 'wheelchair': 'TextEdit', 'brand': 'TextEdit', 'fuel_octan': 'TextEdit', 'opening_ho': 'TextEdit', 'toilets_wh': 'TextEdit', 'country': 'TextEdit', 'target': 'TextEdit', 'phone': 'TextEdit', 'alt_name': 'TextEdit', 'brand_wiki': 'TextEdit', 'brand_wi_1': 'TextEdit', 'takeaway': 'TextEdit', 'bicycle_pa': 'TextEdit', 'access': 'TextEdit', 'smoothness': 'TextEdit', 'surface': 'TextEdit', 'Catering': 'TextEdit', 'delivery': 'TextEdit', 'atm': 'TextEdit', 'natural': 'TextEdit', 'bench': 'TextEdit', 'level': 'TextEdit', 'email': 'TextEdit', 'smoking': 'TextEdit', 'noname': 'TextEdit', 'fee': 'TextEdit', 'operator_t': 'TextEdit', 'contact_ph': 'TextEdit', 'capacity': 'TextEdit', 'name_sw': 'TextEdit', 'internet_a': 'TextEdit', 'studio': 'TextEdit', 'fuel': 'TextEdit', 'denominati': 'TextEdit', 'toilets_ac': 'TextEdit', 'toilets_di': 'TextEdit', 'toilets_ha': 'TextEdit', 'toilets_nu': 'TextEdit', 'man_made': 'TextEdit', 'activities': 'TextEdit', 'ancillary_': 'TextEdit', 'dispensing': 'TextEdit', 'emergency': 'TextEdit', 'healthcare': 'TextEdit', 'healthca_1': 'TextEdit', 'scope': 'TextEdit', 'service_ti': 'TextEdit', 'nature': 'TextEdit', 'network': 'TextEdit', 'building': 'TextEdit', 'tourism': 'TextEdit', 'landuse': 'TextEdit', 'waste': 'TextEdit', 'social_fac': 'TextEdit', 'addr_subwa': 'TextEdit', 'addr_ward': 'TextEdit', 'cash_in': 'TextEdit', 'currency_T': 'TextEdit', 'drive_thro': 'TextEdit', 'Ward': 'TextEdit', 'power': 'TextEdit', 'diet_veget': 'TextEdit', 'diet_vegan': 'TextEdit', 'opening__1': 'TextEdit', 'addr_count': 'TextEdit', 'cash_withd': 'TextEdit', 'self_servi': 'TextEdit', 'toilets': 'TextEdit', });
lyr_KinondoniDistrictBoundary_1.set('fieldLabels', {'Id': 'no label', 'Name': 'no label', });
lyr_HIVHotspost_2.set('fieldLabels', {'full_id': 'no label', 'osm_id': 'no label', 'osm_type': 'no label', 'amenity': 'no label', 'highway': 'no label', 'addr:city': 'no label', 'addr:district': 'no label', 'addr:municipality': 'no label', 'name': 'no label', 'name:en': 'no label', 'religion': 'no label', 'shop': 'no label', 'cargo': 'no label', 'operator': 'no label', 'cuisine': 'no label', 'addr:housename': 'no label', 'addr:housenumber': 'no label', 'addr:postcode': 'no label', 'addr:street': 'no label', 'description': 'no label', 'website': 'no label', 'outdoor_seating': 'no label', 'wheelchair': 'no label', 'brand': 'no label', 'fuel:octane_95': 'no label', 'opening_hours': 'no label', 'toilets:wheelchair': 'no label', 'country': 'no label', 'target': 'no label', 'phone': 'no label', 'alt_name': 'no label', 'brand:wikidata': 'no label', 'brand:wikipedia': 'no label', 'takeaway': 'no label', 'bicycle_parking': 'no label', 'access': 'no label', 'smoothness': 'no label', 'surface': 'no label', 'Catering': 'no label', 'delivery': 'no label', 'atm': 'no label', 'natural': 'no label', 'bench': 'no label', 'level': 'no label', 'email': 'no label', 'smoking': 'no label', 'noname': 'no label', 'fee': 'no label', 'operator:type': 'no label', 'contact:phone': 'no label', 'capacity': 'no label', 'name:sw': 'no label', 'internet_access': 'no label', 'studio': 'no label', 'fuel': 'no label', 'denomination': 'no label', 'toilets:access': 'no label', 'toilets:disposal': 'no label', 'toilets:handwashing': 'no label', 'toilets:num_chambers': 'no label', 'man_made': 'no label', 'activities': 'no label', 'ancillary_services': 'no label', 'dispensing': 'no label', 'emergency': 'no label', 'healthcare': 'no label', 'healthcare:speciality': 'no label', 'scope': 'no label', 'service_times': 'no label', 'nature': 'no label', 'network': 'no label', 'building': 'no label', 'tourism': 'no label', 'landuse': 'no label', 'waste': 'no label', 'social_facility': 'no label', 'addr:subward': 'no label', 'addr:ward': 'no label', 'cash_in': 'no label', 'currency:TZS': 'no label', 'drive_through': 'no label', 'Ward': 'no label', 'power': 'no label', 'diet:vegetarian': 'no label', 'diet:vegan': 'no label', 'opening_hours:kitchen': 'no label', 'addr:country': 'no label', 'cash_withdrawal': 'no label', 'self_service': 'no label', 'toilets': 'no label', 'layer': 'no label', 'path': 'no label', });
lyr_TestingFacilities_3.set('fieldLabels', {'full_id': 'no label', 'osm_id': 'no label', 'osm_type': 'no label', 'amenity': 'no label', 'highway': 'no label', 'addr_city': 'no label', 'addr_distr': 'no label', 'addr_munic': 'no label', 'name': 'no label', 'name_en': 'no label', 'religion': 'no label', 'shop': 'no label', 'cargo': 'no label', 'operator': 'no label', 'cuisine': 'no label', 'addr_house': 'no label', 'addr_hou_1': 'no label', 'addr_postc': 'no label', 'addr_stree': 'no label', 'descriptio': 'no label', 'website': 'no label', 'outdoor_se': 'no label', 'wheelchair': 'no label', 'brand': 'no label', 'fuel_octan': 'no label', 'opening_ho': 'no label', 'toilets_wh': 'no label', 'country': 'no label', 'target': 'no label', 'phone': 'no label', 'alt_name': 'no label', 'brand_wiki': 'no label', 'brand_wi_1': 'no label', 'takeaway': 'no label', 'bicycle_pa': 'no label', 'access': 'no label', 'smoothness': 'no label', 'surface': 'no label', 'Catering': 'no label', 'delivery': 'no label', 'atm': 'no label', 'natural': 'no label', 'bench': 'no label', 'level': 'no label', 'email': 'no label', 'smoking': 'no label', 'noname': 'no label', 'fee': 'no label', 'operator_t': 'no label', 'contact_ph': 'no label', 'capacity': 'no label', 'name_sw': 'no label', 'internet_a': 'no label', 'studio': 'no label', 'fuel': 'no label', 'denominati': 'no label', 'toilets_ac': 'no label', 'toilets_di': 'no label', 'toilets_ha': 'no label', 'toilets_nu': 'no label', 'man_made': 'no label', 'activities': 'no label', 'ancillary_': 'no label', 'dispensing': 'no label', 'emergency': 'no label', 'healthcare': 'no label', 'healthca_1': 'no label', 'scope': 'no label', 'service_ti': 'no label', 'nature': 'no label', 'network': 'no label', 'building': 'no label', 'tourism': 'no label', 'landuse': 'no label', 'waste': 'no label', 'social_fac': 'no label', 'addr_subwa': 'no label', 'addr_ward': 'no label', 'cash_in': 'no label', 'currency_T': 'no label', 'drive_thro': 'no label', 'Ward': 'no label', 'power': 'no label', 'diet_veget': 'no label', 'diet_vegan': 'no label', 'opening__1': 'no label', 'addr_count': 'no label', 'cash_withd': 'no label', 'self_servi': 'no label', 'toilets': 'no label', });
lyr_TestingFacilities_3.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});